apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: book-recommendation-system
  labels:
    app: book-crud-deploy
  name: book-crud-deploy
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: book-crud-deploy
status:
  loadBalancer: {}
