apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: book-recommendation-system
  labels:
    app: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-db
    spec:
      containers:
      - image: postgres
        name: postgres
        resources: {}
        envFrom:
        - configMapRef:
            name: postgresdb-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
status: {}
