apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: postgres-db
  name: postgres-db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-db
status:
  loadBalancer: {}
