apiVersion: v1
kind: Service
metadata:
  name: book-crud-deploy-external  
  namespace: book-recommendation-system
spec:
  type: NodePort
  ports:
    - port: 5000             
      targetPort: 5000       
      protocol: TCP
      nodePort: 30001         
  selector:
    app: book-crud-deploy    

