apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: book-crud-pod
  name: book-crud-pod
spec:
  containers:
  - image: book-crud-service:v0.0.1
    imagePullPolicy: IfNotPresent
    name: book-crud-pod
    ports:
    - containerPort: 8000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
